[build]
  publish = "dist"
  command = "npm run build"

# Redirect /admin to /admin/
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

# Handle /admin/ path properly
[[redirects]]
  from = "/admin/"
  to = "/admin/index.html"
  status = 200
  force = true