backend:
  name: git-gateway
  branch: main
  proxy_url: http://localhost:8081/api/v1

# These lines are optional but recommended for using images
media_folder: "public/images" # Media files will be stored in the repo under public/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "project"
    label: "Projects"
    folder: "src/content/project"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Is Redeemable", name: "isRedeemable", widget: "boolean", default: false}
      - {label: "Redeem URL", name: "redeemUrl", widget: "string", required: false}
      - {label: "Images", name: "images", widget: "list", required: false, fields: [{label: "Image", name: "image", widget: "image"}]}
      - {label: "Slider", name: "slider", widget: "list", required: false, fields: [{label: "Image", name: "image", widget: "image"}]}

  - name: "prints"
    label: "Prints"
    folder: "src/content/prints"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Currency", name: "currency", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Paper", name: "paper", widget: "string"}
      - {label: "Edition", name: "edition", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Digital Goods", name: "digital_goods", widget: "boolean"}
      - {
          label: "Shipping",
          name: "shipping",
          widget: "object",
          fields:
            [
              {label: "Weight", name: "weight", widget: "number"},
              {label: "Width", name: "width", widget: "number"},
              {label: "Length", name: "length", widget: "number"},
              {label: "Height", name: "height", widget: "number"},
            ],
        }
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean"}
