backend:
  name: test-repo

# Global media folder settings
media_folder: "/public/assets"
public_folder: "/assets"

# This line is important for local development
local_backend: true

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "project"
    label: "Projects"
    folder: "src/content/project"
    create: true
    format: frontmatter
    extension: md
    media_folder: "/public/assets"
    public_folder: "/assets"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Collection", name: "collection", widget: "hidden", default: "project"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown", required: true}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Is Redeemable", name: "isRedeemable", widget: "boolean", default: false}
      - {label: "Redeem URL", name: "redeemUrl", widget: "string", required: false}
      - label: "Project Image"
        name: "image"
        widget: "image"
        choose_url: true
        required: false
        media_folder: "/public/assets/{{fields.slug}}"
        public_folder: "/assets/{{fields.slug}}"
      - label: "Images"
        name: "images"
        widget: "list"
        required: false
        summary: "{{fields.image}}"
        field:
          label: "Image"
          name: "image"
          widget: "image"
          choose_url: true
          media_folder: "/public/assets/{{fields.slug}}"
          public_folder: "/assets/{{fields.slug}}"
          allow_multiple: false
      - {label: "Slider", name: "slider", widget: "list", required: false, field: {label: "Image Number", name: "image", widget: "string"}}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "prints"
    label: "Prints"
    folder: "src/content/prints"
    create: true
    format: frontmatter
    extension: md
    media_folder: "public/assets/prints"
    public_folder: "/assets/prints"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Currency", name: "currency", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: true
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Paper", name: "paper", widget: "string"}
      - {label: "Edition", name: "edition", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Digital Goods", name: "digital_goods", widget: "boolean"}
      - {
          label: "Shipping",
          name: "shipping",
          widget: "object",
          fields:
            [
              {label: "Weight", name: "weight", widget: "number"},
              {label: "Width", name: "width", widget: "number"},
              {label: "Length", name: "length", widget: "number"},
              {label: "Height", name: "height", widget: "number"},
            ],
        }
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
